version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    depends_on:
      - mongodb

  bookmark-service:
    build: ./bookmark-service
    ports:
      - "5002:5002"
    depends_on:
      - mongodb

  media-service:
    build: ./media-service
    ports:
      - "5003:5003"

  search-service:
    build: ./search-service
    ports:
      - "5004:5004"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
